### ISSUE TITLE
BUG: Caller not instrumented with javaagent

### ISSUE THREAD

**Issue by dwing4g** [offbynull/coroutines#77] opened 2017-03-04 13:02 UTC
public final class TestFiber2 {
    public static final class TestFiber3 implements Coroutine     {
        @Override
        public void run(Continuation c) throws Exception {
            c.suspend();
        }
    }
    private static final java.util.ArrayDeque<CoroutineRunner> _readyQueue = new java.util.ArrayDeque<>();
    public static void submit(Coroutine c) {
        _readyQueue.offer(new CoroutineRunner(c));
    }
    public static void main(String[] args) {
        TestFiber3 f = new TestFiber3();
        submit(c -> {
            submit(f);
            c.suspend();
        });
        while(!_readyQueue.isEmpty())
            _readyQueue.poll().execute();
    }
}

java -javaagent:java-agent-1.2.2-shaded.jar -cp user-1.2.2.jar;. TestFiber2

Exception in thread "main" com.offbynull.coroutines.user.CoroutineException: Exception thrown during execution
        at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:60)
        at TestFiber2.main(TestFiber2.java)
Caused by: java.lang.UnsupportedOperationException: Caller not instrumented
        at com.offbynull.coroutines.user.Continuation.suspend(Continuation.java:256)
        at TestFiber2$TestFiber3.run(TestFiber2.java)
        at com.offbynull.coroutines.user.CoroutineRunner.execute(CoroutineRunner.java:56)
        ... 1 more

**Comment by offbynull** [comment] 2017-03-04 13:47
I'll look at this shortly.

**Comment by dwing4g** [comment] 2017-03-04 14:36
Thank you for your quick reply.
It's the minimum version to reproduce this bug.
Moving the inner class outside or submitting the TestFiber3 coroutine first will run well.

**Comment by dwing4g** [comment] 2017-03-04 14:43
In fact, I also encountered some other bugs with my test code(also with javaagent).

1. Starting with this exception:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "test/TestFiber"

2. sometimes new object became null after suspend().

**Comment by offbynull** [comment] 2017-03-04 16:36
Okay. I was able to reproduce the error and did some debugging. So far, it looks like everything is correct on my end. The JVM, however, seems to be discarding my bytecode instrumentation changes after the first time execute() gets called.

I know this because I updated the agent to dump the class after it instruments it. The call to suspend no longer exists in the instrumented version (this is correct), but the stacktrace shows that it still gets called.

I'm a bit confused as to what might be going on here. I'll do some more investigation.

**Comment by offbynull** [comment] 2017-03-04 17:13
I might have spoken too soon. Looks like the inner class isn't making it to the instrumenter.

**Comment by offbynull** [comment] 2017-03-04 17:57
Okay. So it seems like what's happening is that the Java agent ClassFileTransformer isn't picking up TestFiber3 if it gets called from within a lambda...

The following works...
```java
        submit(c -> {
            c.suspend();
        });
        submit(new TestFiber3());
```

But, the original doesn't work because TestFiber3 is invoked from a lambda....
```java
        TestFiber3 f = new TestFiber3();
        submit(c -> {
            submit(f);
            c.suspend();
        });
```

This seems to be on the JVM-side behaviour and seems totally wrong.

**Comment by offbynull** [comment] 2017-03-04 18:12
As for the other problems you mentioned -- I suspect they were happening because I was accidentally instrumenting internal coroutines classes. That part I've fixed, but the agent won't be usable until I figure out a work around for the TestFiber3 lambda issue.

**Comment by offbynull** [comment] 2017-03-04 20:01
Further investigation: The problem of TestFiber2$TestFiber3 not being visible to ClassFileTransformer happens only have TestFiber2 is instrumented.

**Comment by offbynull** [comment] 2017-03-04 21:03
I found out what's happening.

If ClassFileTransformer calls Class.forName(...) on a class that hasn't been transformed yet, it will never get passed to that ClassFileTransformer. In our case, when we transform TestFiber2, we need to call Class.forName on TestFiber2$TestFiber3.

This is what's stopping TestFiber2$TestFiber3 from getting instrumented.

**Comment by offbynull** [comment] 2017-03-04 22:26
There's probably a way around this problem. It'll take some time to figure out.

In the meantime I suggest you use one of the plugins.

**Comment by offbynull** [comment] 2017-03-05 16:09
I got some tips from Remi on the ASM mailing list on how to work around this problem. I'll try implementing them to see how they work.

**Comment by offbynull** [comment] 2017-03-05 17:32
It looks like Remi's insights have paid off. Here's a successful execution run of your example with the fixed Java agent. I'll commit and cut a new release so you can test.


```java
import com.offbynull.coroutines.user.Continuation;
import com.offbynull.coroutines.user.Coroutine;
import com.offbynull.coroutines.user.CoroutineRunner;

public final class TestFiber2 {

    public static final class TestFiber3 implements Coroutine {

        @Override
        public void run(Continuation c) throws Exception {
            c.suspend();
        }
    }
    private static final java.util.ArrayDeque<CoroutineRunner> _readyQueue = new java.util.ArrayDeque<>();

    public static void submit(Coroutine c) {
        _readyQueue.offer(new CoroutineRunner(c));
    }

    public static void main(String[] args) {
        TestFiber3 f = new TestFiber3();
        submit(c -> {
            submit(f);
            c.suspend();
        });
        while (!_readyQueue.isEmpty()) {
            System.out.println("executing...");
            _readyQueue.poll().execute();
            System.out.println("finished...");
        }
    }
}
```


```shell
java -javaagent:C:\Users\User\Documents\NetBeansProjects\coroutines\java-agent\target\java-agent-1.2.3-SNAPSHOT-shaded.jar=STDOUT,false -cp ..\..\coroutines\user\user-1.2.3-SNAPSHOT.jar;. TestFiber2 > out.txt
```


```
TestFiber2 false
TestFiber2$TestFiber3 false
executing...
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Getting state for switch
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Case 0 -- Fresh invocation
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Jump to start of method point
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Starting method...
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving SUSPEND 0
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving operand stack
Saving operand stack (1 items)
Generating objects container (1)
Popping/storing object at 0 to storage index 0
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving locals
Saving locals
Generating objects container (2)
Inserting object at LVT index 0 to storage index 0
Inserting object at LVT index 1 to storage index 1
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Packing locals and operand stack in to container
Packing storage arrays for locals and operand stack in to an Object[]
Putting locals objects in to container
Putting stack objects in to container
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Creating and pushing method state
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Setting mode to save
TestFiber2-lambda$main$0-(LTestFiber2$TestFiber3;Lcom/offbynull/coroutines/user/Continuation;)V >>> Returning (dummy return value if not void)
finished...
executing...
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Getting state for switch
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Case 0 -- Fresh invocation
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Jump to start of method point
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Starting method...
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving SUSPEND 0
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving operand stack
Saving operand stack (1 items)
Generating objects container (1)
Popping/storing object at 0 to storage index 0
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Saving locals
Saving locals
Generating objects container (2)
Inserting object at LVT index 0 to storage index 0
Inserting object at LVT index 1 to storage index 1
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Packing locals and operand stack in to container
Packing storage arrays for locals and operand stack in to an Object[]
Putting locals objects in to container
Putting stack objects in to container
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Creating and pushing method state
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Setting mode to save
TestFiber2$TestFiber3-run-(Lcom/offbynull/coroutines/user/Continuation;)V >>> Returning (dummy return value if not void)
finished...

```

**Comment by offbynull** [comment] 2017-03-05 19:29
Release 1.2.3 is available. Please download and let me know how if it works for you.

**Comment by dwing4g** [comment] 2017-03-06 05:36
Thanks very much for your new version.
My test code runs very well with v1.2.3.

I rewrote a microbenchmark(https://github.com/atemerev/skynet) by your coroutine library.
The result is amazing! Only takes 300ms on my i7-4790(3.6GHz) and JDK8.

BTW: I also look into another small enough async library(and a loader in another library):
https://github.com/electronicarts/ea-async
https://github.com/electronicarts/ea-agent-loader
That looks similar with yours in some way, and it has a runtime way for instrumentation without javaagent.
I hope it helps you to make your coroutine better.

**Comment by offbynull** [comment] 2017-03-07 03:59
Thank you for the kind words, but you should be careful when you do these types of benchmarks -- alot of the times it's apples and oranges.

I'll take a look at those projects when I have a moment to spare. I'll close this ticket tmrw EOD.

**Closed** 2017-03-08 01:49 UTC
